CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.METADATA;

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.METADATA.INGESTION_RUN_LOG (
    RUN_ID STRING,
    SOURCE_SYSTEM STRING,
    SOURCE_DATABASE STRING,
    SOURCE_SCHEMA STRING,
    TARGET_DATABASE STRING,
    TARGET_SCHEMA STRING,
    LOAD_MODE STRING,
    STARTED_AT TIMESTAMP_TZ,
    FINISHED_AT TIMESTAMP_TZ,
    STATUS STRING,
    ERROR_MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.METADATA.INGESTION_TABLE_CATALOG (
    RUN_ID STRING,
    SOURCE_SYSTEM STRING,
    SOURCE_DATABASE STRING,
    SOURCE_SCHEMA STRING,
    SOURCE_TABLE STRING,
    TARGET_DATABASE STRING,
    TARGET_SCHEMA STRING,
    TARGET_TABLE STRING,
    SOURCE_ROW_COUNT NUMBER,
    TARGET_ROW_COUNT NUMBER,
    ROW_COUNT_MATCH BOOLEAN,
    LOAD_STATUS STRING,
    LOAD_SECONDS FLOAT,
    LOADED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.METADATA.INGESTION_COLUMN_CATALOG (
    RUN_ID STRING,
    SOURCE_SYSTEM STRING,
    SOURCE_DATABASE STRING,
    SOURCE_SCHEMA STRING,
    SOURCE_TABLE STRING,
    SOURCE_COLUMN STRING,
    SOURCE_ORDINAL_POSITION NUMBER,
    SOURCE_DATA_TYPE STRING,
    SOURCE_CHARACTER_MAXIMUM_LENGTH NUMBER,
    SOURCE_NUMERIC_PRECISION NUMBER,
    SOURCE_NUMERIC_SCALE NUMBER,
    SOURCE_IS_NULLABLE STRING,
    TARGET_DATABASE STRING,
    TARGET_SCHEMA STRING,
    TARGET_TABLE STRING,
    TARGET_COLUMN STRING,
    TARGET_DATA_TYPE STRING,
    CATALOGED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.METADATA.INGESTION_VALIDATION_RESULTS (
    RUN_ID STRING,
    SOURCE_SYSTEM STRING,
    TARGET_DATABASE STRING,
    TARGET_SCHEMA STRING,
    TARGET_TABLE STRING,
    VALIDATION_NAME STRING,
    VALIDATION_STATUS STRING,
    VALIDATION_VALUE STRING,
    VALIDATED_AT TIMESTAMP_TZ
);