CREATE OR REPLACE VIEW DATA_VALIDATION.METADATA.V_LATEST_INGESTION_RUN AS
SELECT *
FROM DATA_VALIDATION.METADATA.INGESTION_RUN_LOG
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SOURCE_SYSTEM, SOURCE_DATABASE, SOURCE_SCHEMA, TARGET_DATABASE, TARGET_SCHEMA
    ORDER BY STARTED_AT DESC
) = 1;


CREATE OR REPLACE VIEW DATA_VALIDATION.METADATA.V_TABLE_CATALOG_LATEST AS
SELECT
    t.*
FROM DATA_VALIDATION.METADATA.INGESTION_TABLE_CATALOG t
JOIN DATA_VALIDATION.METADATA.V_LATEST_INGESTION_RUN r
    ON t.RUN_ID = r.RUN_ID;


CREATE OR REPLACE VIEW DATA_VALIDATION.METADATA.V_COLUMN_CATALOG_LATEST AS
SELECT
    c.*
FROM DATA_VALIDATION.METADATA.INGESTION_COLUMN_CATALOG c
JOIN DATA_VALIDATION.METADATA.V_LATEST_INGESTION_RUN r
    ON c.RUN_ID = r.RUN_ID;


CREATE OR REPLACE VIEW DATA_VALIDATION.METADATA.V_COLUMN_SEARCH AS
SELECT
    SOURCE_SYSTEM,
    SOURCE_DATABASE,
    SOURCE_SCHEMA,
    SOURCE_TABLE,
    SOURCE_COLUMN,
    SOURCE_DATA_TYPE,
    TARGET_DATABASE,
    TARGET_SCHEMA,
    TARGET_TABLE,
    TARGET_COLUMN,
    TARGET_DATA_TYPE,
    CATALOGED_AT
FROM DATA_VALIDATION.METADATA.V_COLUMN_CATALOG_LATEST;