CREATE OR REPLACE VIEW DATA_VALIDATION.METADATA.V_POTENTIAL_RELATIONSHIP_COLUMNS AS
SELECT
    TARGET_COLUMN,
    COUNT(DISTINCT TARGET_TABLE) AS TABLE_COUNT,
    LISTAGG(DISTINCT TARGET_TABLE, ', ')
        WITHIN GROUP (ORDER BY TARGET_TABLE) AS TABLES
FROM DATA_VALIDATION.METADATA.V_COLUMN_SEARCH
WHERE TARGET_COLUMN ILIKE '%ID'
   OR TARGET_COLUMN ILIKE '%NUMBER'
   OR TARGET_COLUMN IN (
        'PROJECTID',
        'STAGEID',
        'QUOTEID',
        'DEALID',
        'JOBNUMBER',
        'ITEMNUMBER',
        'INVOICEID',
        'CUSTOMER',
        'EMAIL'
   )
GROUP BY TARGET_COLUMN
HAVING COUNT(DISTINCT TARGET_TABLE) > 1;