CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.SEMANTIC;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_ESTIMATE_QAD" AS
SELECT
    *,
'ESTIMATE' AS _SEMANTIC_ENTITY_NAME,
'IDG_ESTIMATE_QAD' AS _SEMANTIC_SOURCE_TABLE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ESTIMATE_QAD";

CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.SEMANTIC;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_INVOICE_QAD" AS
SELECT
    *,
'INVOICE' AS _SEMANTIC_ENTITY_NAME,
'IDG_INVOICE_QAD' AS _SEMANTIC_SOURCE_TABLE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_INVOICE_QAD";

CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.SEMANTIC;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_ORDER_QAD" AS
SELECT
    *,
'ORDER' AS _SEMANTIC_ENTITY_NAME,
'IDG_ORDER_QAD' AS _SEMANTIC_SOURCE_TABLE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ORDER_QAD";

CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.SEMANTIC;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_ESTIMATE_LINE_QAD" AS
SELECT
    *,
'ESTIMATE_LINE' AS _SEMANTIC_ENTITY_NAME,
'IDG_SARASOTA_ESTIMATE_LINE_QAD' AS _SEMANTIC_SOURCE_TABLE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_SARASOTA_ESTIMATE_LINE_QAD";
