CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.SEMANTIC;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_BRIDGE_ESTIMATE_TO_SARASOTA_ESTIMATE_LINE_QAD" AS
SELECT DISTINCT
    NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') AS PARENT_KEY_VALUE,
    NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '') AS CHILD_KEY_VALUE,
    'IDG_ESTIMATE_QAD' AS _SEMANTIC_PARENT_TABLE,
    'IDG_SARASOTA_ESTIMATE_LINE_QAD' AS _SEMANTIC_CHILD_TABLE,
    'ESTIMATE_NUMBER' AS _SEMANTIC_PARENT_COLUMN,
    'ESTIMATE_NUMBER' AS _SEMANTIC_CHILD_COLUMN,
    'N:M' AS _SEMANTIC_CARDINALITY_TYPE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ESTIMATE_QAD" p
JOIN DATA_VALIDATION.RAW_REDSHIFT."IDG_SARASOTA_ESTIMATE_LINE_QAD" c
  ON NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') =
     NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '')
WHERE NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') IS NOT NULL
  AND NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '') IS NOT NULL;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_SUMMARY_ESTIMATE_TO_SARASOTA_ESTIMATE_LINE_QAD" AS
SELECT
    NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') AS PARENT_KEY_VALUE,
    COUNT(*) AS JOINED_ROW_COUNT,
    COUNT(DISTINCT NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '')) AS DISTINCT_CHILD_KEY_COUNT,
    'IDG_ESTIMATE_QAD' AS _SEMANTIC_PARENT_TABLE,
    'IDG_SARASOTA_ESTIMATE_LINE_QAD' AS _SEMANTIC_CHILD_TABLE,
    'ESTIMATE_NUMBER' AS _SEMANTIC_PARENT_COLUMN,
    'ESTIMATE_NUMBER' AS _SEMANTIC_CHILD_COLUMN,
    'N:M' AS _SEMANTIC_CARDINALITY_TYPE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ESTIMATE_QAD" p
JOIN DATA_VALIDATION.RAW_REDSHIFT."IDG_SARASOTA_ESTIMATE_LINE_QAD" c
  ON NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') =
     NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '')
WHERE NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') IS NOT NULL
  AND NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '') IS NOT NULL
GROUP BY 1;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_BRIDGE_ORDER_TO_INVOICE_QAD" AS
SELECT DISTINCT
    NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') AS PARENT_KEY_VALUE,
    NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '') AS CHILD_KEY_VALUE,
    'IDG_ORDER_QAD' AS _SEMANTIC_PARENT_TABLE,
    'IDG_INVOICE_QAD' AS _SEMANTIC_CHILD_TABLE,
    'ESTIMATE_NUMBER' AS _SEMANTIC_PARENT_COLUMN,
    'ESTIMATE_NUMBER' AS _SEMANTIC_CHILD_COLUMN,
    'N:M' AS _SEMANTIC_CARDINALITY_TYPE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ORDER_QAD" p
JOIN DATA_VALIDATION.RAW_REDSHIFT."IDG_INVOICE_QAD" c
  ON NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') =
     NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '')
WHERE NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') IS NOT NULL
  AND NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '') IS NOT NULL;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_SUMMARY_ORDER_TO_INVOICE_QAD" AS
SELECT
    NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') AS PARENT_KEY_VALUE,
    COUNT(*) AS JOINED_ROW_COUNT,
    COUNT(DISTINCT NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '')) AS DISTINCT_CHILD_KEY_COUNT,
    'IDG_ORDER_QAD' AS _SEMANTIC_PARENT_TABLE,
    'IDG_INVOICE_QAD' AS _SEMANTIC_CHILD_TABLE,
    'ESTIMATE_NUMBER' AS _SEMANTIC_PARENT_COLUMN,
    'ESTIMATE_NUMBER' AS _SEMANTIC_CHILD_COLUMN,
    'N:M' AS _SEMANTIC_CARDINALITY_TYPE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ORDER_QAD" p
JOIN DATA_VALIDATION.RAW_REDSHIFT."IDG_INVOICE_QAD" c
  ON NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') =
     NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '')
WHERE NULLIF(TRIM(TO_VARCHAR(p."ESTIMATE_NUMBER")), '') IS NOT NULL
  AND NULLIF(TRIM(TO_VARCHAR(c."ESTIMATE_NUMBER")), '') IS NOT NULL
GROUP BY 1;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_BRIDGE_ORDER_TO_INVOICE_QAD" AS
SELECT DISTINCT
    NULLIF(TRIM(TO_VARCHAR(p."PO_NUMBER")), '') AS PARENT_KEY_VALUE,
    NULLIF(TRIM(TO_VARCHAR(c."PO_NUMBER")), '') AS CHILD_KEY_VALUE,
    'IDG_ORDER_QAD' AS _SEMANTIC_PARENT_TABLE,
    'IDG_INVOICE_QAD' AS _SEMANTIC_CHILD_TABLE,
    'PO_NUMBER' AS _SEMANTIC_PARENT_COLUMN,
    'PO_NUMBER' AS _SEMANTIC_CHILD_COLUMN,
    'N:M' AS _SEMANTIC_CARDINALITY_TYPE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ORDER_QAD" p
JOIN DATA_VALIDATION.RAW_REDSHIFT."IDG_INVOICE_QAD" c
  ON NULLIF(TRIM(TO_VARCHAR(p."PO_NUMBER")), '') =
     NULLIF(TRIM(TO_VARCHAR(c."PO_NUMBER")), '')
WHERE NULLIF(TRIM(TO_VARCHAR(p."PO_NUMBER")), '') IS NOT NULL
  AND NULLIF(TRIM(TO_VARCHAR(c."PO_NUMBER")), '') IS NOT NULL;

CREATE OR REPLACE VIEW DATA_VALIDATION.SEMANTIC."V_SUMMARY_ORDER_TO_INVOICE_QAD" AS
SELECT
    NULLIF(TRIM(TO_VARCHAR(p."PO_NUMBER")), '') AS PARENT_KEY_VALUE,
    COUNT(*) AS JOINED_ROW_COUNT,
    COUNT(DISTINCT NULLIF(TRIM(TO_VARCHAR(c."PO_NUMBER")), '')) AS DISTINCT_CHILD_KEY_COUNT,
    'IDG_ORDER_QAD' AS _SEMANTIC_PARENT_TABLE,
    'IDG_INVOICE_QAD' AS _SEMANTIC_CHILD_TABLE,
    'PO_NUMBER' AS _SEMANTIC_PARENT_COLUMN,
    'PO_NUMBER' AS _SEMANTIC_CHILD_COLUMN,
    'N:M' AS _SEMANTIC_CARDINALITY_TYPE
FROM DATA_VALIDATION.RAW_REDSHIFT."IDG_ORDER_QAD" p
JOIN DATA_VALIDATION.RAW_REDSHIFT."IDG_INVOICE_QAD" c
  ON NULLIF(TRIM(TO_VARCHAR(p."PO_NUMBER")), '') =
     NULLIF(TRIM(TO_VARCHAR(c."PO_NUMBER")), '')
WHERE NULLIF(TRIM(TO_VARCHAR(p."PO_NUMBER")), '') IS NOT NULL
  AND NULLIF(TRIM(TO_VARCHAR(c."PO_NUMBER")), '') IS NOT NULL
GROUP BY 1;
