source:
  name: ENDEAVOR
  type: sqlserver
  env_prefix: ENDEAVOR
  database: EndeavorDB
  schema: dbo

target:
  database: DATA_VALIDATION
  schema: RAW_SQL_SERVER
  table_suffix: _ENDEAV

load:
  mode: full_refresh
  chunk_size: 50000
  include_tables:
    - __EFMigrationsHistory
    - Actions
    - Appointments
  exclude_empty_tables: true

incremental:
  enabled: true
  default_strategy: full_refresh

  tables:
    Actions:
      strategy: timestamp
      watermark_column: ChangeDate

    StatusDetails:
      strategy: timestamp
      watermark_column: Timestamp

    ProjectNotes:
      strategy: timestamp
      watermark_column: Timestamp

    E4Jobs:
      strategy: timestamp
      watermark_column: Updated

metadata:
  database: DATA_VALIDATION
  schema: METADATA

validation:
  row_count: true
  fail_on_row_count_mismatch: false