CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE;

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE.COLUMN_PROFILE (
    PROFILE_RUN_ID VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    TARGET_DATABASE VARCHAR,
    TARGET_SCHEMA VARCHAR,
    TARGET_TABLE VARCHAR,
    TARGET_COLUMN VARCHAR,
    DATA_TYPE VARCHAR,
    ROW_COUNT NUMBER,
    NON_NULL_COUNT NUMBER,
    NULL_COUNT NUMBER,
    DISTINCT_COUNT NUMBER,
    DISTINCT_RATIO FLOAT,
    NON_NULL_RATIO FLOAT,
    MIN_VALUE VARCHAR,
    MAX_VALUE VARCHAR,
    PROFILED_AT TIMESTAMP_TZ
);