CREATE SCHEMA IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE;

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE.COLUMN_PROFILE (
    PROFILE_RUN_ID VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    TARGET_DATABASE VARCHAR,
    TARGET_SCHEMA VARCHAR,
    TARGET_TABLE VARCHAR,
    TARGET_COLUMN VARCHAR,
    DATA_TYPE VARCHAR,
    ROW_COUNT NUMBER,
    NON_NULL_COUNT NUMBER,
    NULL_COUNT NUMBER,
    DISTINCT_COUNT NUMBER,
    DISTINCT_RATIO FLOAT,
    NON_NULL_RATIO FLOAT,
    MIN_VALUE VARCHAR,
    MAX_VALUE VARCHAR,
    PROFILED_AT TIMESTAMP_TZ
);


CREATE TABLE IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE.KEY_CANDIDATES (
    PROFILE_RUN_ID VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    TARGET_DATABASE VARCHAR,
    TARGET_SCHEMA VARCHAR,
    TARGET_TABLE VARCHAR,
    TARGET_COLUMN VARCHAR,
    DATA_TYPE VARCHAR,
    CANDIDATE_TYPE VARCHAR,
    CONFIDENCE_SCORE FLOAT,
    REASON VARCHAR,
    CREATED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE.RELATIONSHIP_CANDIDATES (
    RELATIONSHIP_RUN_ID VARCHAR,
    PROFILE_RUN_ID VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    PARENT_TABLE VARCHAR,
    PARENT_COLUMN VARCHAR,
    CHILD_TABLE VARCHAR,
    CHILD_COLUMN VARCHAR,
    MATCH_COUNT NUMBER,
    CHILD_NON_NULL_COUNT NUMBER,
    MATCH_RATE FLOAT,
    CONFIDENCE_SCORE FLOAT,
    CONFIDENCE_LABEL VARCHAR,
    DISCOVERY_METHOD VARCHAR,
    CREATED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE.ENTITY_MAP (
    ENTITY_NAME VARCHAR,
    SOURCE_SYSTEM VARCHAR,
    TARGET_TABLE VARCHAR,
    ENTITY_ROLE VARCHAR,
    CONFIDENCE_LABEL VARCHAR,
    CREATED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS DATA_VALIDATION.INTELLIGENCE.RELATIONSHIP_GRAPH (
    SOURCE_SYSTEM VARCHAR,
    FROM_TABLE VARCHAR,
    FROM_COLUMN VARCHAR,
    TO_TABLE VARCHAR,
    TO_COLUMN VARCHAR,
    RELATIONSHIP_TYPE VARCHAR,
    CONFIDENCE_LABEL VARCHAR,
    MATCH_RATE FLOAT,
    CREATED_AT TIMESTAMP_TZ
);